// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imqdhxllbugnwgpraevk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltcWRoeGxsYnVnbndncHJhZXZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MTYwMjksImV4cCI6MjA3NDI5MjAyOX0.AAQOw3ax27FpVCBhBBQLo7U2ZyjeJ3tV6VZQvR60Jvo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});